# Generated by Django 5.0.6 on 2024-06-24 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Salas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sala", models.CharField(max_length=50)),
                ("inicio", models.DateTimeField(auto_now_add=True)),
                ("prazo", models.DateTimeField()),
                ("fim", models.DateTimeField()),
            ],
        ),
    ]
